### ISSUE TITLE
Archived Versions

### ISSUE THREAD

**Issue by harryoppy** [wyot1/GeoLite2-Unwalled#1]
Thanks for putting this together - is there any way to get versions of this data from the past year?

**Comment by wyot1** [comment]
What are you working on that needs old geo data?

The official downloads go back 30 days.

My releases are auto-deleted after roughly a month as well, because I don't want to get in trouble with github for spamming, and to keep git lean (It's really not meant for that.).

Technically more exist until github decides to really-really purge. But that's out of user control.

I looked for you and found this guy slapped the last few years on archive.org. I can imagine ways that are less wasteful, but it has what you want.: https://archive.org/details/@vloup
Since IA archives all kinds of real junk I suppose this is even one of the more legit uses.

If you want them archived going forward as well, I recommend automating the download using the master lists here. Then you can upload the big block to IA next time :).

**Comment by harryoppy** [comment]
Wow - thank you so much. I'm a postdoc at Los Alamos and Lawrence Livermore
studying technology and international security. Next year I will be a
professor at Georgia Tech. I'm matching data on Russian control over data
routes in Ukraine to data on conflict and local territorial control. To do
that accurately I need to get a good mapping to ASes to geographical scope
(since my routing data is at the AS-level). Since the mappings can change I
need to be able to reliably do that over time.

**Comment by wyot1** [comment]
Interesting.
By the way, this usually works better for very large downloads from the IA:
https://archive.org/developers/internetarchive/cli.html#download

Not sure it handles resuming, though.

**Comment by wyot1** [comment]
Closing since you have what you need.

I wondered if it'd be reasonable to archive them on the IA automatically. But the IA is extremely buggy in my experience, so that'd likely be a mess to automate.
